apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ollama
  labels:
    app: fastapi-ollama
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-ollama
  template:
    metadata:
      labels:
        app: fastapi-ollama
    spec:
      containers:
      - name: fastapi-ollama
        image: fastapi-ollama:latest
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "production"