apiVersion: v1
kind: Service
metadata:
  name: fastapi-ollama-service
  labels:
    app: fastapi-ollama
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: fastapi-ollama